name: "Matrix test"

on:
  workflow_dispatch:
    inputs:
      versions:
        type: choice
        description: "lol"
        options:
          - "10"

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON('["10"]') }}
        os: [ubuntu-latest]
    steps:
    - name: print matrix
      run: |
        echo ${{ matrix.version }} ${{ matrix.os }}
        echo ${{ fromJSON('[${{ inputs.versions }}]') }}
