name: "Matrix test"

on:
  workflow_dispatch:
    inputs:
      versions:
        type: choice
        description: "lol"
        options:
          - '["10"]'
          - '["12"]'
          - '["13"]'

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON('${{ inputs.versions }}') }}
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: print matrix
      run: |
        echo ${{ matrix.version }} ${{ matrix.os }}
