name: "Matrix test"

on:
  schedule:
    - cron: "*/2 * * * *"
    
  workflow_dispatch:
    inputs:
      versions:
        type: choice
        description: "lol"
        options:
          - '["10", "12", "14"]'

env:
  VER: ${{ inputs.versions || '["10", "12", "14"]' }}

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON($VER) }}
        os: [ubuntu-latest]
    steps:
    - name: print matrix
      run: |
        echo ${{ matrix.version }} ${{ matrix.os }}
