name: "Matrix test"

on:
  workflow_dispatch: { }

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: print matrix
      run: |
        echo ${{ matrix.version }} ${{ matrix.os }}
