name: Run Docker compose

on:
  workflow_dispatch:

jobs:
  release_port:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "release port 8084"
      run: |
        sudo systemctl stop mono-xsp4.service 
        sudo systemctl disable mono-xsp4.service
        sudo kill $(ps aux | grep /usr/bin/mono | grep www-data | awk '{print $2}')
        sudo netstat -lpn

