name: Run Docker compose

on:
  workflow_dispatch:
    inputs:
      version:
        description: Select a version
        type: choice
        options:
          - 1
          - 2
          - 3
      compose_file:
        description: select app to build
        type: choice
        options:
          - docker-compose.yml
          - docker-compose-second.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Update packages"
      run: |
        sudo apt-get update
    
    - uses: actions/checkout@v4
    - name: "Install Docker compose"
      run: |
        # sudo apt-get install docker-compose -y;
        # docker-compose --version
        pwd;
        ls -al;
        echo "Selected version: ${{ github.event.inputs.version }}";
        echo "Selected version: ${{ github.event.inputs.compose_file }}";
    
    - name: "Install OpenJDK"
      run: |
        sudo apt-get install openjdk-11-jdk -y;
        java --version;