name: Run Docker compose

on:
  workflow_dispatch:
    inputs:
      version:
        description: Select a version
        type: choice
        options:
          - 1
          - 2
          - 3
      compose_file:
        description: select app to build
        type: choice
        options:
          - docker-compose.yml
          - docker-compose-second.yml
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout main repo"
      uses: actions/checkout@v4

    - name: "Checkout second repo"
      uses: actions/checkout@v4
      with:
        repository: WelderWDE/docker_learn
        path: "docker_learn"
        ref: refs/heads/main
    
    - name: "listdir"
      run: ls -al

    # - name: "Update packages"
    #   run: |
    #     sudo apt-get update

    # - name: "Install Docker compose"
    #   run: |
    #     # sudo apt-get install docker-compose -y;
    #     # docker-compose --version
    #     pwd;
    #     # ls -al;
    #     # echo "Selected version: ${{ github.event.inputs.version }}";
    #     # echo "Selected version: ${{ github.event.inputs.compose_file }}";
    
    # - name: "Install OpenJDK"
    #   run: |
    #     sudo apt-get install openjdk-11-jdk -y;
    #     java --version;

    - name: "Check everything"
      run: |
        docker compose
        # docker --version;
        # docker-compose --version;
        # java --version;
        # ls -al
