name: "Triggered workflow"

on:
  pull_request: { }

jobs:
  default_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print text
        run: >
          url="https://"${{ secrets.TEST }};
          echo $url;
